accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:user_pk>/mypage/", views.mypage, name="mypage"), # 마이페이지
    path("password/", views.password, name='password'), # 비밀번호 변경
    path("delete/", views.delete, name="delete"),    # 회원탈퇴
    path("<int:pk>/update/", views.update, name="update"),
]

community/urls.py
from django.urls import path
from . import views

app_name = "community"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path('<int:pk>/like/', views.like, name="like"),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path("<int:article_pk>/comments/<int:comment_pk>/like/", views.comment_like, name="comment_like"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
    path("community/", include("community.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/models.py
from django.db import models
from django.contrib.auth import get_user_model  # from accounts.models import User
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length=40)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    image = ProcessedImageField(upload_to='images/', blank=True, null=True,
                                processors=[ResizeToFill(400, 300)],
                                format='JPEG', options={'quality': 90})
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_article')
    view_count = models.IntegerField(default=0)

class Photo(models.Model):
    article = models.ForeignKey(Articles, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to="images/", blank=True, null=True)

class Comments(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    article = models.ForeignKey(Articles, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_comment"
    )
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True)

community/forms.py
from django import forms
from .models import *
from django.forms import ClearableFileInput

class ArticlesForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = [
            "title",
            "content",
        ]
        labels = {
            "title": "제목",
            "content": "내용",
        }

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ("image",)
        widgets = {
            "image": ClearableFileInput(attrs={"multiple": True}),
        }

class CommentsForm(forms.ModelForm):
    content = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "댓글을 작성해주세요.",
        })
    )
    class Meta:
        model = Comments
        fields = ['content',]

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *
from django.http import JsonResponse
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    articles = Articles.objects.order_by("-pk")
    page = request.GET.get("page", "1")
    paginator = Paginator(articles, 10)
    page_obj = paginator.get_page(page)
    context = {
        "articles": page_obj,
    }
    return render(request, "community/index.html", context)


def detail(request, pk):
    article = get_object_or_404(Articles, pk=pk)
    default_view_count = article.view_count
    article.view_count = default_view_count + 1
    article.save()
    comment_form = CommentsForm()
    comments = article.comments_set.filter(parent_comment=None)
    replies= article.comments_set.exclude(parent_comment=None)

    context = {
        "article": article,
        "comments": comments,
        "replies": replies,
        "comment_form": comment_form,
        "photo_cnt": article.photo_set.count(),
    }

    return render(request, "community/detail.html", context)


@login_required
def create(request):
    if request.method == "POST":
        article_form = ArticlesForm(request.POST, request.FILES)
        photo_form = PhotoForm(request.POST, request.FILES)
        images = request.FILES.getlist("image")

        if article_form.is_valid() and photo_form.is_valid():
            article = article_form.save(commit=False)
            article.user = request.user
            if len(images):
                for image in images:
                    image_instance = Photo(article=article, image=image)
                    article.save()
                    image_instance.save()
            else:
                article.save()
            return redirect("community:index")
    else:
        article_form = ArticlesForm()
        photo_form = PhotoForm()
    context = {
        "article_form": article_form,
        "photo_form": photo_form,
    }
    return render(request, "community/create.html", context)



@login_required
def update(request, pk):
    article = Articles.objects.get(pk=pk)
    photos = Photo.objects.filter(article_id=article.pk)
    if request.user != article.user:
        from django.http import HttpResponseForbidden
        return HttpResponseForbidden()
    if request.method == "POST":
        article_form = ArticlesForm(request.POST, request.FILES, instance=article)
        photo_form = PhotoForm(request.POST, request.FILES)
        images = request.FILES.getlist("image")

        for photo in photos:
            if photo.image:
                photo.delete()
        if article_form.is_valid() and photo_form.is_valid():
            article = article_form.save(commit=False)         
            if len(images):
                for image in images:
                    image_instance = Photo(article=article, image=image)
                    article.save()
                    image_instance.save()
            else:
                article.save()
            return redirect("community:detail", pk)
    else:
        article_form = ArticlesForm(instance=article)
        if photos:
            photo_form = PhotoForm(instance=photos[0])
        else:
            photo_form = PhotoForm()

    context = {
        "article_form": article_form,
        "photo_form": photo_form,
    }
    return render(request, "community/create.html", context)


@login_required
def delete(request, pk):
    article = Articles.objects.get(pk=pk)

    if request.user != article.user:
        return redirect("community:index")

    if request.method == "POST":
        if request.user == article.user:
            article.delete()
            return redirect("community:index")
    else:
        return redirect("community:detail", pk)


@login_required
def like(request, pk):
    article = Articles.objects.get(pk=pk)
    if article.like_users.filter(id=request.user.id).exists():
        article.like_users.remove(request.user)
        is_liked = False
    else:
        article.like_users.add(request.user)
        is_liked = True
    context = {
        'isLiked': is_liked,
        'likeCount': article.like_users.count()
    }
    return JsonResponse(context)


@login_required
def comment_create(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Articles, pk=pk)
        comment_form = CommentsForm(request.POST)
        parent_comment_id = request.POST.get('parent_comment_id', None)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.parent_comment_id = parent_comment_id
            comment.save()
            return redirect('community:detail', article.pk)
    return redirect('community:login')


@login_required
def comment_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        article = Articles.objects.get(pk=article_pk)
        comment = Comments.objects.get(pk=comment_pk)
        replies = article.comments_set.filter(parent_comment=comment)

        if request.user == comment.user:
            comment.delete()
    return redirect('community:detail', article_pk)


@login_required
def comment_update(request, article_pk, comment_pk):
    comment = Comments.objects.get(pk=comment_pk)
    comment_form = CommentsForm(instance=comment)
    if request.user != comment.user:
        from django.http import HttpResponseForbidden
        return HttpResponseForbidden()
    if request.method == "POST":
        form = CommentsForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('community:detail', article_pk)
    else:
        form = CommentsForm(instance=comment)
    return render('community:comment_update', {"form": form})


@login_required
def comment_like(request, article_pk, comment_pk):
    comment = get_object_or_404(Comments, pk=comment_pk)
    article = Articles.objects.get(pk=article_pk)
    if request.user in comment.like_users.all():
        comment.like_users.remove(request.user)
    else:
        comment.like_users.add(request.user)
    return redirect("community:detail", article_pk)

community/templates/community/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block css %}
  <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/css/star-rating.min.css" media="all" rel="stylesheet" type="text/css"/>
  <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/themes/krajee-svg/theme.css" media="all" rel="stylesheet" type="text/css"/>
{% endblock css %}

{% block content %}
  <div class="p-4">
    <div class="d-flex justify-content-center align-items-center">
      <h1 class="me-4 my-4">글 작성</h1>
    </div>
    <div class="d-flex justify-content-center">
      <div class="col-md-12 col-lg-8">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form article_form %}
          {% bootstrap_form photo_form %}
          <div class="mt-2 d-flex justify-content-end">
            {% bootstrap_button button_type="submit" content="등록" %}
            <a href="{% url 'community:index' %}" class="btn btn-outline-secondary ms-2">뒤로가기</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

community/templates/community/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}
{% load mathfilters %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
{% endblock css %}

{% block content %}
  <div class="p-4">
    <div class="row justify-content-center">
      <div class="col-md-12 col-lg-8">
        <div class="p-3 mb-4" style="border-radius: 0.5rem; box-shadow: 1px 1px 5px rgba(0, 0, 0, 0.5); background-color: white;">
          <h2 class="mb-1 fw-bolder">{{ article.title }}</h2>
            <div>
              <p class="fw-light mb-1 text-end" style="font-size: 1rem;">
                작성자 : <a href="{% url 'accounts:detail' article.user.pk %}">{{ article.user.nickname }}</a>
              </p>
            </div>
          <div class="d-flex justify-content-end mt-1">
            <p class="fw-light mb-1 text-end" style="font-size: 0.7rem;">
              작성 
              {{ article.created_at|date:'Y-m-d H:i' }}
              | 수정
              {{ article.updated_at|date:'Y-m-d H:i' }}
            </p>
          </div>
          <div>
            <hr class="mt-2">
            {% for photo in article.photo_set.all %}
              <img src="{{ photo.image.url }}" alt="{{ photo.image }}" class="mb-3" style="max-width:100%; height:auto">
            {% endfor %}
            <p class="mt-3">{{ article.content }}</p>
          </div>

          <!-- 좋아요 버튼 -->
          <div class="d-flex justify-content-center mt-4 mb-2">
            {% if request.user.is_authenticated %}
              {% if request.user in article.like_users.all %}
              <div>
                <i id="like-btn" data-article-id="{{ article.pk }}" class="bi bi-heart-fill btn btn-danger" style="background-color: #FF617B; font-style: normal;"><span class="ms-1" id="like-count">{{ article.like_users.count }}</span></i>
              </div>
              {% else %}
              <div>
                <i id="like-btn" data-article-id="{{ article.pk }}" class="bi bi-heart btn btn-outline-danger" style="font-style: normal;"><span class="ms-1" id="like-count">{{ article.like_users.count }}</span></i>
              </div>
              {% endif %}
            {% else %}
            <a href="#" class="btn btn-outline-primary"><i class="bi bi-heart"><span id="like-count"> {{ article.like_users.count }}</span></i></a>
            {% endif %}
          </div>

          <!-- 댓글창 -->
          <div>
            <h5 style="margin-bottom: 1rem;">댓글 ({{ article.comments_set.all.count }})</h5>
            {% if request.user.is_authenticated %}
            <form id="comment-form" action="{% url 'community:comment_create' article.pk %}" method="POST">
                {% csrf_token %}
              <div class="d-flex justify-content-end">
                {{ comment_form.content|add_class:'form-control' }}
                <input class="btn btn-sm btn-outline-primary ms-3" type="submit" value="등록">
              </div>
            </form>
            {% else %}
              <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
            {% endif %}
            <hr>
          </div>

          <!-- 댓글 목록 -->
          <div>
            {% for comment in comments %}
              <div class="mb-2 d-flex justify-content-between">
                <div class="w-100">
                  <div class="d-flex justify-content-between">
                    <div class="w-100">
                      <p style="font-size: 0.8rem; margin-bottom: 0rem;">
                        <a href="{% url 'accounts:detail' article.user.pk %}">{{ comment.user.nickname }}</a> | {{ comment.created_at|date:'Y-m-d H:i' }}
                      </p>
                      <p style="margin-bottom: 0rem;">{{ comment.content }}</p>
                    </div>

                    <!-- 댓글 좋아요 버튼 -->
                    {% if request.user.is_authenticated %}
                      <a class="like-heart mt-2 mx-2" href="{% url 'community:comment_like' article.pk comment.pk %}">
                      {% if request.user in comment.like_users.all %}
                        <i class="bi bi-heart-fill"></i>
                      {% else %}
                        <i class="bi bi-heart"></i>
                      {% endif %}
                      </a>
                    {% else %}
                      <a href="{% url 'accounts:login' %}" class="mx-2">
                        <i class="bi bi-heart"></i>
                      </a>
                    {% endif %}
                      
                    <!-- 댓글 삭제 버튼 -->
                    {% if user == comment.user %}
                      <form action="{% url 'community:comment_delete' article.pk comment.pk %}" method="POST" class="d-inline mt-1">
                        {% csrf_token %}
                        <button class="btn btn-none border-0 p-0" type="submit">
                          <img src="{% static 'images/bin.png' %}" style="width: 24px">
                        </button>
                      </form>
                    {% endif %}
                  </div>
  
                  <div class="d-flex mb-0" style="font-size: 0.7rem;">
                    <a href="#replyBox{{ comment.pk }}" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseExample">
                      답글 달기
                    </a>
                    <p class="mx-3 mb-0">좋아요 {{ comment.like_users.count }}개</p>
                  </div>
                  
                  <!-- 답글 창 펼치기 -->
                  <div class="collapse" id="replyBox{{ comment.pk }}">
                    <div class="mt-2">
                      {% if request.user.is_authenticated %}
                        <form action="{% url 'community:comment_create' article.pk %}" method="POST">
                          {% csrf_token %}
                          <input type="hidden" name="parent_comment_id" value="{{ comment.pk }}">
                          
                          <div class="d-flex" style="width: 100%;">
                            {{ comment_form.content|add_class:'form-control' }}
                            <input class="btn btn-sm btn-outline-primary ms-3" type="submit" value="등록">
                          </div>
                        </form>
                      {% else %}
                        <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
                      {% endif %}
                    </div>
                  </div>
                  
                  <!-- 답글 목록 -->
                    {% for reply in replies %}
                      {% if reply.parent_comment == comment %}
                      <div class="d-flex mt-2 justify-content-between">
                        <div class="d-flex w-100">
                          <div class="pt-1 ps-2">
                            <i class="bi bi-arrow-return-right"></i>
                          </div>
                          <div class="ms-3 w-100">
                            <p style="font-size: 0.8rem; margin-bottom: 0rem;">
                              <a href="{% url 'accounts:detail' article.user.pk %}">{{ reply.user.nickname }}</a> | {{ reply.created_at|date:'Y-m-d H:i' }}
                            </p>
                            <p style="margin-bottom: 0rem;">{{ reply.content }}</p>
                            <div class="d-flex mb-0" style="font-size: 0.7rem;">
                              <p class="mb-0">좋아요 <span id="comment-{{ reply.pk }}-like-count">{{ reply.like_users.count }}</span>개</p>
                            </div>
                          </div>
                        </div>

                        <div class="d-flex mt-2">
                          <!-- 댓글 좋아요 버튼 -->
                        {% if request.user.is_authenticated %}
                          <a class="like-heart mt-2 mx-2" href="{% url 'community:comment_like' article.pk comment.pk %}">
                          {% if request.user in reply.like_users.all %}
                            <i class="bi bi-heart-fill"></i>
                          {% else %}
                            <i class="bi bi-heart"></i>
                          {% endif %}
                          </a>
                        {% else %}
                          <a href="{% url 'accounts:login' %}" class="mx-2">
                            <i class="bi bi-heart"></i>
                          </a>
                        {% endif %}

                        <!-- 댓글 삭제 버튼 -->
                        {% if user == reply.user %}
                          <form action="{% url 'community:comment_delete' article.pk comment.pk %}" method="POST" class="d-inline mt-1">
                            {% csrf_token %}
                            <button class="btn btn-none border-0 p-0" type="submit">
                              <img src="{% static 'images/bin.png' %}" style="width: 24px">
                            </button>
                          </form>
                        {% endif %}
                        </div>
                      </div>


                      {% endif %}
                    {% endfor %}
                </div>
  
              </div>
              {% empty %}
              <p>댓글이 아직 없어요.</p>
            {% endfor %}
          </div>
        </div>

        <!-- 글 수정 & 삭제 & 뒤로가기 -->
        <div class='d-flex justify-content-end'>
        {% if request.user == article.user or request.username == 'admin' %}
          <form action="{% url 'community:delete' article.pk %}" method="POST" class="form">
            {% csrf_token %}
            <div class="d-block d-lg-none">
              <a href="{% url 'community:update' article.pk %}" class="btn btn-outline-primary form-control mb-3">수정</a>
              <input class="btn btn-outline-danger form-control mb-3" type="submit" value="삭제">
              <a href="{% url 'community:index' %}" class="btn btn-outline-secondary form-control mb-3">뒤로</a>
            </div>
            <div class="d-none d-lg-block">
              <a href="{% url 'community:update' article.pk %}" class="btn btn-outline-primary">수정</a>
              <input class="btn btn-outline-danger" type="submit" value="삭제">
              <a href="{% url 'community:index' %}" class="btn btn-outline-secondary">뒤로</a>
            </div>
          </form>
        {% else %}
          <div class="d-block d-lg-none">
            <a href="{% url 'community:index' %}" class="btn btn-outline-secondary form-control mb-3">뒤로</a>
          </div>
          <div class="d-none d-lg-block">
            <a href="{% url 'community:index' %}" class="btn btn-outline-secondary">뒤로</a>
          </div>
        {% endif %}
        </div>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    // 좋아요 버튼
    const likeBtn = document.querySelector('#like-btn')
    // 좋아요 버튼을 누르면 함수 실행
    likeBtn.addEventListener('click', function(event) {
      // 서버로 비동기 요청
      axios({
        method: 'get',
        url: `/community/${event.target.dataset.articleId}/like/`
      })
      .then(response => {
        if (response.data.isLiked === true) {
          event.target.classList.add('bi-heart-fill')
          event.target.classList.remove('bi-heart')
        } else {
          event.target.classList.add('bi-heart')
          event.target.classList.remove('bi-heart-fill')
        }
        const likeCount = document.querySelector('#like-count')
        likeCount.innerText = response.data.likeCount
      })
    })
  </script>
  <script>
    // 댓글 좋아요
    const CommnetLikeBtn = document.querySelector('#comment-like-btn')
    // 좋아요 버튼을 누르면 함수 실행
    CommnetLikeBtn.addEventListener('click', function(event) {
      // 서버로 비동기 요청
      axios({
        method: 'get',
        url: `/community/${event.target.dataset.articleId}/comments/${event.target.dataset.commentId}/like/`
      })
      .then(response => {
        if (response.data.isLiked === true) {
          event.target.classList.add('bi-heart-fill')
          event.target.classList.remove('bi-heart')
        } else {
          event.target.classList.add('bi-heart')
          event.target.classList.remove('bi-heart-fill')
        }
        const CommentlikeCount = document.querySelector('#like-count')
        CommentlikeCount.innerText = response.data.CommentlikeCount
      })
    })
  </script>
  {% comment %} <script>
    // 댓글 비동기
    const commentForm = document.querySelector('#comment-form')
    commentForm.addEventListener('submit', function(event) {
      event.preventDefault();
      axios({
        method: 'post',
        url: `/articles/${event.target.dataset.articleId}/comments/`
      })
    })
  </script> {% endcomment %}
{% endblock content %}

community/templates/community/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{% endblock css %}

{% block content %}
  <div class="container">
    <div class="pt-4">

        <table class="table table-hover rounded-5" style="">
        <thead style="background: #70d7e740; border-top: 0px solid #ccc; border-bottom: 2px solid #004af14a; font-weight: bold;">
            <tr style="text-align: center;">
            <th scope="col">번호</th>
            <th scope="col">제목</th>
            <th scope="col">작성일</th>
            <th scope="col">작성자</th>
            <th scope="col">조회수</th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
            <tr>
                <!-- <th scope="row" class="align-middle col-md-1">{{ forloop.revcounter }}</td> -->
                <th scope="row" class="align-middle col-md-1" style="text-align: center;">{{ article.pk }}</td>
                <td class="align-middle col-md-7">
                <a href="{% url 'community:detail' article.pk %}" class="text-decoration-none">{{ article.title }}</a><span class="text-muted"> ({{ article.comments_set.all.count }})</span>
                </td>
                <td class="align-middle col-md-1" style="text-align: center;">{{ article.created_at|date:'m.d' }}</td>
                <td class="align-middle col-md-1" style="text-align: center;"><a href="{% url 'accounts:detail' article.user.pk %}">{{ article.user.nickname }}</a></a></td>
                <td class="align-middle col-md-1" style="text-align: center;">{{ article.view_count }}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
    <div class="d-flex justify-content-end">
      <a href="{% url 'community:create' %}">
        <button type="button" class="btn btn-outline-primary">글쓰기</button>
      </a>
    </div>
    <!--페이징-->
    <ul class="pagination pagination justify-content-center">
      <!--이전페이지-->
      {% if articles.has_previous %}
      <li class="page-item">
        <a href="?page={{ articles.previous_page_number }}" class="page-link">이전</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a href="#" class="page-link" aria-disabled="true">이전</a>
      </li>
      {% endif %}
      <!--페이지리스트-->
      {% for page_number in articles.paginator.page_range %}
      {% if page_number >= articles.number|add:-5 and page_number <= articles.number|add:5 %}
        {% if page_number == articles.number %}
        <li class="page-item active" aria-current="page">
          <a href="?page={{ page_number }}" class="page-link">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
      {% endif %}
      {% endfor %}
      <!--다음페이지-->
      {% if articles.has_next %}
      <li class="page-item">
        <a href="?page={{ articles.next_page_number }}" class="page-link">다음</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a href="#" class="page-link" aria-disabled="true">다음</a>
      </li>
      {% endif %}
    </ul>
  </div>
  
{% endblock content %}