accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:user_pk>/mypage/", views.mypage, name="mypage"), # 마이페이지
    path("password/", views.password, name='password'), # 비밀번호 변경
    path("delete/", views.delete, name="delete"),    # 회원탈퇴
    path("<int:pk>/update/", views.update, name="update"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
    path("community/", include("community.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    nickname = models.CharField(max_length=20, unique=True, null=True)
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    intro = models.TextField(blank=True)  # 소개글
    image = ProcessedImageField(
        blank=True,
        upload_to="profile/",
        processors=[ResizeToFill(300, 300)],
        format="JPEG",
        options={"quality": 60},
    )

    def __str__(self):
        return self.user.email

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from .models import Profile
from django.forms import ModelForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "nickname",)
        labels = {
            "nickname": "닉네임",
        }

    # OperationalError at /accounts/signup/
    # no such column: accounts_user.nickname
    def signup(self, request, user):
        # form에 기입된 데이터를 가져오기 위해 cleaned_data 사용
        user.nickname = self.cleaned_data["nickname"]
        user.save()


class ProfileForm(ModelForm):
    class Meta:
        model = Profile()
        fields = ['intro', 'image']


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ["nickname"]
        labels = {
            "nickname": "닉네임",
        }

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile
from .forms import CustomUserCreationForm, ProfileForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib import messages
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .forms import CustomUserChangeForm
from django.http import JsonResponse


# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect("articles:index")

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)  # 프로필 생성
            auth_login(request, user)
            return redirect("articles:index")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.user.is_authenticated:
        return redirect("articles:index")

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "articles:index")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    messages.warning(request, "로그아웃 되었습니다.")
    return redirect("articles:index")


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    articles = user.article_set.all()
    like_articles = user.like_articles.all()
    bookmark_articles = user.bookmark_articles.all()
    articles_count = len(articles)
    like_articles_count = len(like_articles)
    bookmark_articles_count = len(bookmark_articles)

    context = {
        "user": user,
        "articles": articles,
        "like_articles": like_articles,
        "bookmark_articles": bookmark_articles,
        "articles_count": articles_count,
        "like_articles_count": like_articles_count,
        "bookmark_articles_count": bookmark_articles_count,
    }
    return render(request, "accounts/detail.html", context)


@require_POST
@login_required
def follow(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)

    # 프로필에 해당하는 유저를 로그인한 유저가 팔로우 할 수 없음
    if request.user == user:
        messages.warning(request, "스스로 팔로우 할 수 없습니다.")
        return redirect("accounts:detail", pk)

    # 팔로우 상태면, 팔로우 취소를 누르면 삭제
    if request.user in user.followers.all():
        user.followers.remove(request.user)
        is_followed = False

    # 팔로우 상태가 아니면, '팔로우'를 누르면 추가
    else:
        user.followers.add(request.user)
        is_followed = True

    data = {
        "followers_count": user.followers.count(),
        "followings_count": user.followings.count(),
        "is_followed": is_followed,
    }

    return JsonResponse(data)


# 마이 페이지 (회원 정보로 이동, 비밀번호 변경, 로그아웃, 회원탈퇴)
@login_required
def mypage(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)

    if request.user != user:
        return redirect("articles:index")

    context = {
        "user": user,
    }

    return render(request, "accounts/mypage.html", context)


# 비밀번호 변경
@login_required
def password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)  # 로그인 유지
            return redirect("accounts:mypage", request.user.pk)

    else:
        form = PasswordChangeForm(request.user)

    context = {
        "form": form,
    }

    return render(request, "accounts/password.html", context)


# 회원 탈퇴
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)

    return redirect("articles:index")


# 회원 프로필 (프로필 사진, 소개글) (+ 닉네임?)
@login_required
def update(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)

    # 업데이트
    if request.user.profile:
        profile = request.user.profile

        if request.method == "POST":
            profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
            change_form = CustomUserChangeForm(request.POST, instance=user)

            if profile_form.is_valid() and change_form.is_valid():
                profile_form.save()
                change_form.save()
                # return redirect('accounts:detail', request.user.pk)
                return redirect("accounts:mypage", request.user.pk)

        else:
            profile_form = ProfileForm(instance=profile)
            change_form = CustomUserChangeForm(instance=user)

    # 최초 생성
    else:
        if request.method == "POST":
            profile_form = ProfileForm(request.POST, request.FILES)
            change_form = CustomUserChangeForm(request.POST, instance=user)

            if profile_form.is_valid() and change_form.is_valid():
                profile_form.save()
                change_form.save()
                # return redirect('accounts:detail', request.user.pk)
                return redirect("accounts:mypage", request.user.pk)

        else:
            profile_form = ProfileForm()
            change_form = CustomUserChangeForm(instance=user)

    context = {
        "profile_form": profile_form,
        "change_form": change_form,
    }

    return render(request, "accounts/update.html", context)


@login_required
def articles(request, pk):
    articles = all.Articles.objects.filter(user=request.user).order_by("-pk")
    context = {
        "articles": articles,
    }
    return render(request, "accounts/articles.html", context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock css %}



{% block content %}


<body style="background-color: #FAFAFA;height: 100%">
  <div style="font-size: 14px;text-align: center;width: 100%;min-height: 100vh;display: flex; flex-direction: row;  justify-content: center;">
    <div class="mt-4">
    <div>
      <div class="mb-3" style="background-color: white; width: 350px; height: 400px; border: 1px solid rgba(0, 0, 0, 0.18);">
        <div style="display: flex;align-items: center;justify-content: center">
          <img style="height: 50px; object-fit: contain; margin: 30px 0" src="{% static 'images/logo.jpg' %}">
        </div>

  <form class="mb-3" action="{% url 'accounts:login' %}" method="POST" enctype="multipart/form-data"
    style="font-size:14px;">
    {% csrf_token %}
    <div class="my-3 px-3">
      <input type="text" style="height: 46px; border: 1.5px solid rgb(221, 221, 222);" name="username" autofocus=""
        autocapitalize="none" autocomplete="username" maxlength="150" class="form-control" placeholder="아이디를 입력해주세요"
        required="" id="id_username">
    </div>
    <div class="my-3 px-3">
      <input type="password" style="height: 46px; border: 1.5px solid rgb(221, 221, 222);" name="password"
        autocomplete="current-password" class="form-control" placeholder="비밀번호를 입력해주세요" required="" id="id_password">
    </div>
    <div class="px-3">
    <input type="submit" class="btn py-2 px-3 form-control fw-bold" style="background-color: #263088; color: white"
      value="로그인">
  </form>
  </div>
  <div class="px-3">
  <a href="{% url 'accounts:signup' %}"> <input class="btn py-2 form-control fw-bold"
      style="border:2px solid #1b1c8b;background-color: white; color: #5e0080" value="회원가입"></a>
    </div>
    </div>
</section>

{% endblock content %}

accounts/templates/accounts/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="list-group">
    <a href="{% url 'accounts:detail' request.user.pk %}" class="list-group-item list-group-item-action">
      <div class="d-flex align-items-center">
        {% if user.profile.image %}
          <img src="{{ user.profile.image.url }}" alt="{{ user.profile.image }}" class="rounded-2 border border-1" width="48px">
        {% else %}
          <img src="{% static 'images/dummy-image-square.jpg' %}" alt="" class="rounded-2 border border-1" width="48px">
        {% endif %}

        <span class="ms-3">{{ user.nickname }}</span>
      </div>
    </a>
    <a href="{% url 'accounts:password' %}" class="list-group-item list-group-item-action">비밀번호 변경</a>
    <a href="{% url 'accounts:logout' %}" class="list-group-item list-group-item-action">로그아웃</a>
    <a href="{% url 'accounts:delete' %}" class="list-group-item list-group-item-action">회원탈퇴</a>
  </div>
{% endblock content %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class="text-center my-5">비밀번호 변경</h1>

  <form action="" method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}

    <div class="text-end">
      <input type="submit" value="변경하기" class="btn btn-primary">
    </div>
  </form>
{% endblock %}

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
    

<head>
    {% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>



</head>
<body style="background-color: #FAFAFA;height: 100%">
    <section class="container" style="width: 640px;height: 1315px; margin-top: 100px;">
        <!-- <h2 class="d-flex justify-content-center my-5">회원가입</h2> -->
        <div>
          <div style="display: flex;align-items: center;justify-content: center">
              <h2>𝖙𝖗𝖎𝖕𝖘𝖙𝖆𝖗𝖌𝖗𝖆𝖒</h2>
           
        </div>
        <div>
          <form class="mx-3" action="{% url 'accounts:signup' %}"
            style="border-top: 0px solid rgb(51, 51, 51); font-size:14px;" method="POST">
            {% csrf_token %}
            <div class="d-flex align-items-center">
              <h6 class="my-3" style="width: 123px; color: rgb(51, 51, 51); font-size:14px;">아이디</h6>
              <div class="my-3">
                <input type="text" style="width: 333px; height: 46px;" name="username" maxlength="150" autofocus=""
                  class="signup-input form-control" placeholder="아이디를 입력해주세요" required="" id="id_username">
              </div>
              </div>
              <div class="d-flex align-items-center">
                  <h6 class="my-3" style="width:123px; color: rgb(51, 51, 51); font-size:14px;">닉네임</h6>
                  <div class="my-3">
                    <input type="text" style="width:333px; height: 46px;" name="nickname" class="signup-input form-control"
                      placeholder="닉네임을 입력해주세요" requird="" id="id_nickname">
                  </div>
      
      
            </div>
            <div class="d-flex align-items-center">
              <h6 class="my-3" style="width: 123px; color: rgb(51, 51, 51); font-size: 14px;">비밀번호</h6>
              <div class="my-3">
                <input type="password" style="width:333px; height: 46px;"  name="password1" autocomplete="new-password"
                  class="signup-input form-control" placeholder="비밀번호를 입력해주세요" required="" id="id_password1">
              </div>
            </div>
            <div class="d-flex align-items-center">
              <h6 class="my-3" style="width: 123px; color: rgb(51, 51, 51); font-size: 14px;">비밀번호 확인</h6>
              <div class="my-3">
                <input type="password" style="width:333px; height: 46px;" name="password2" autocomplete="new-password"
                  class="signup-input form-control" placeholder="비밀번호를 한 번 더 입력해주세요" required="" id="id_password2">
              </div>
            </div>
            <div class="d-flex justify-content-center my-3">
              <input type="submit" class="btn py-2 px-5 fw-bold form-control"
                style="border-radius:0px; height:56px; background-color: #6365cf; color: white" value="가입하기">
            </div>
          </form>
        </div>
        <hr>
        <div class="d-flex justify-content-center align-items-center">
          <p class='mb-0' style="color: rgba(194, 200, 204, 1)">이미 회원이라면? <a class="text-decoration-none"
              style="color:#5e0080" href="{% url 'accounts:login' %}">로그인</a></p>
        </div>
      
      </section>
      
      
      
      
</body>
</html>
      

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class="text-center my-5">회원 정보 수정</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form profile_form %}
    {% bootstrap_form change_form %}

    <div class="text-end">
      <input type="submit" class="btn btn-primary" value="완료">
    </div>
  </form>
{% endblock content %}