accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:user_pk>/mypage/", views.mypage, name="mypage"), # 마이페이지
    path("password/", views.password, name='password'), # 비밀번호 변경
    path("delete/", views.delete, name="delete"),    # 회원탈퇴
    path("<int:pk>/update/", views.update, name="update"),
]

articles/urls.py
# URL설정을 app 단위로!
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/like/", views.like, name="like"),
    path("<int:pk>/bookmark/", views.bookmark, name="bookmark"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path(
        "<int:article_pk>/comments/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path(
        "<int:article_pk>/comments/<int:comment_pk>/like/",
        views.comment_like,
        name="comment_like",
    ),
    path("search/", views.search, name="search"),
    path("roulette/", views.roulette, name="roulette"),
]

community/urls.py
from django.urls import path
from . import views

app_name = "community"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path('<int:pk>/like/', views.like, name="like"),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path("<int:article_pk>/comments/<int:comment_pk>/like/", views.comment_like, name="comment_like"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
    path("community/", include("community.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}?{% now 'U' %}">
    {% block css %}{% endblock css %}
    <!-- Icons -->
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <title>𝖙𝖗𝖎𝖕𝖘𝖙𝖆𝖗𝖌𝖗𝖆𝖒</title>
    <style>
      .navi_profile_box {
        width: 50px;
        height: 50px;
        border-radius: 70%;
        overflow: hidden;
        cursor: pointer;
    }

    .profile_img {
      width: 100%;
      height: 100%;
      object-fit: fill;
  }
    </style>
  </head>

  <body style="background-color:  #FAFAFA;">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-white" style="background-color: #70d7e740;">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'articles:index' %}">
          <div class="d-flex align-items-center">
            <img src="{% static 'images/logo.jpg' %}" alt="logo" height="50px" width="150px">
          </div>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
          <div>
            <ul class="navbar-nav">
              <li class="nav-item">
                {% if request.resolver_match.app_name == 'community' and request.resolver_match.url_name == 'index' %}
                  <a class="nav-link active" href="{% url 'community:index' %}">커뮤니티</a>
                {% else %}
                  <a class="nav-link" href="{% url 'community:index' %}">커뮤니티</a>
                {% endif %}
              </li>

              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
                </li>
              {% else %}
                <li class="nav-item">
                  {% if request.resolver_match.url_name == 'signup' %}
                    <a class="nav-link active" href="{% url 'accounts:signup' %}">회원가입</a>
                  {% else %}
                    <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                  {% endif %}
                </li>
                <li class="nav-item">
                  {% if request.resolver_match.url_name == 'login' %}
                    <a class="nav-link active" href="{% url 'accounts:login' %}">로그인</a>
                  {% else %}
                    <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                  {% endif %}
                </li>
              {% endif %}
              <li class="nav-item">
                <form role="search" action="{% url 'articles:search' %}" class="p-1">
                  <div class="d-flex justify-content-center">
                    <select class="form-select w-auto" name="search_option">
                      <option value="title">제목</option>
                      <option value="title_content">제목+내용</option>
                      <option value="hashtag">해시태그</option>
                      <option value="user">작성자</option>
                    </select>

                    <input class="form-control w-10 mx-2" type="search" placeholder="Search" name="search">
                    <input class="btn btn-success" type="submit" value="검색">
                  </div>
                </form>
              </li>
            </ul>
          </div>


            <ul class="navbar-nav">
              <div class="d-flex align-items-center">
                <li class="nav-item">
                  {% if request.resolver_match.app_name == 'articles' and request.resolver_match.url_name == 'index' %}
                    <a class="nav-link active" href="{% url 'articles:index' %}">
                      <span class="material-icons navi_icons go_home">home</span></a>
                  {% else %}
                    <a class="nav-link" href="{% url 'articles:index' %}">
                      <span class="material-icons navi_icons go_home">home</span></a>
                  {% endif %}
                </li>
                <li class="nav-item">
                  {% if request.user.is_authenticated %}
                  <a class="nav-link active" href="{% url 'articles:create' %}">
                    <span class="material-icons-outlined navi_icons">add_box</span></a>
                    {% else %}
                    <a class="nav-link active" href="{% url 'accounts:login' %}">
                      <span class="material-icons-outlined navi_icons">add_box</span></a>
                    </a>
                    {% endif %}
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:mypage' request.user.pk %}">
                    <div class="d-flex align-items-center">
                      <span class="me-2 mb-1">{{ request.user.nickname }}</span>
                      <div class="navi_profile_box">
                      {% if request.user.profile.image %}
                        <img src="{{ request.user.profile.image.url }}" class="profile_img">
                      {% else %}
                        <img src="{% static 'images/dummy-image-square.jpg' %}" class="profile_img">
                      {% endif %}
                      </div>
                    </div>
                  </a>
                </li>
              </div>
            </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>

  <!-- Content -->
  <div class="container my-5">
    {% block content %}{% endblock content %}
  </div>

  <!-- JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <!-- JQuery -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <!-- Axios -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <!-- Moment.js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
  <!-- Scripts -->
  {% block script %}{% endblock script %}
</body>

</html>